#!/usr/bin/env bash

tester() {
    step "Testando rede..."
    if ping 8.8.8.8 -c 1 &>/dev/null; then
        success "Conexão ativa. Continuando..."
    else
        error "Internet desconectada. Saindo com status 1"
    fi
}

ins() {
    tester
    CMD="-S"
    TAG="[INSTALLED]"
    FLAT_CMD="install flathub"
}
rmv() {
    CMD="-R"
    TAG="[REMOVED]"
    FLAT_CMD="uninstall"
}
upd() {
    tester
    CMD="-Syu"
    TAG="[UPDATED]"
    FLAT_CMD="update"
}
rfs() {
    tester
    CMD="-Syy"
    TAG="[REFRESHED]"
}