#!/usr/bin/env bash

clr_cache() {
    if [[ -d "$REAL_HOME/.cache/yay" ]]; then
        step "Limpando builds do AUR..."
        find "$REAL_HOME/.cache/yay" -maxdepth 1 -type d \
        -not -path "$REAL_HOME/.cache/yay" -exec rm -rf {} +
        success "Builds limpos."
    fi
    if command -v flatpak &>/dev/null; then
        step "Limpando sobras de Flatpaks..."
        flatpak uninstall --unused -y &>/dev/null
        success "Flatpaks limpos."
    fi
    step "Limpando cache do pacman..."
    CMD="-Scc"
    TAG="CLEANED CACHE"
}

remove_orphans() {
    step "Buscando pacotes orfãos..."
    mapfile -t FINAL_ARGS < <(yay -Qqtd 2>/dev/null)
    ORPHANS_N=${#FINAL_ARGS[@]}
    if [[ "$ORPHANS_N" -eq 0 ]]; then
        success "Nenhum pacote orfão encontrado"
        logger "SEARCHED ORPHANS" "clean"
        exit 0
    fi
    echo "$NOTE $ORPHANS_N Orfãos encontrados"
    printf '%s\n' "${FINAL_ARGS[@]}"
    step "Removendo Orfãos..."
    CMD="-Rsn"
    TAG="REMOVED ORPHANS"
}

check_conf() {
    step "Buscando arquivos .pacnew/.pacsave..."
    PACNEWS=$(find /etc -regextype posix-extended \
    -regex ".+\.pac(new|save)" 2>/dev/null)
    if [[ -z "$PACNEWS" ]]; then
        success "Tudo limpo! Nenhum conflito em /etc."
    else
        echo -e "${YELLOW} $NOTE Arquivos pendentes encontrados:${NC}"
        echo "$PACNEWS"
        echo -e "\n${CYAN} $CC ${NC}Mesclar agora com pacdiff? [y/N]"
        read -r -n 1 opt
        echo
        [[ "$opt" =~ ^(y|Y)$ ]] && sudo pacdiff
    fi
    TAG="CLEAR DIFFS"
}