#!/usr/bin/env bash

list_aur() {
    CMD="-Qm"
    TAG="[LOCAL_QUERY (AUR)]"
}

refresh_mirrors() {
    tester
    echo "$WARNING Procurando mirrors..."
    sudo cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak
    sudo reflector --country Brazil --latest 10 --sort rate --save /etc/pacman.d/mirrorlist
    echo "$OK Mirrors atualizados"
    exit 0
}