#!/usr/bin/env bash

searcher() {
    tester
    CMD="-Ss"
    TAG="SEARCHED"
    FLAT_CMD="search"
}

query() {
    CMD="-Qs"
    TAG="LOCAL QUERY"
    [[ "$LIST_AUR" == true ]] && list_aur && TAG="SKIP" && return
}

check_updates() {
    tester
    step "Searching for updates..."
    UPDS="$(checkupdates 2>/dev/null)"
    UPDS_N=$(echo "$UPDS" | wc -l)
    if [[ "$UPDS_N" == "0" ]]; then
        success "0 Updates found."
        exit 0
    fi
    echo -e "${YELLOW} $NOTE $UPDS_N Updates found:${NC}"
    echo "$UPDS"
    logger "FOUND UPDATES" "$UPDS_N updates"
}
